backend:
  name: github
  repo: void-echo/yu
  branch: main
  auth_endpoint: /api/auth
  base_url: https://wangy.pages.dev

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
local_backend: true           # 允许本地开发时测试，可以保留
locale: 'zh_Hans'             # 后台界面语言，'zh_Hant' 是繁体中文，'zh_Hans' 是简体
collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "文章标题", name: "title", widget: "string"}
      - label: "发布日期"
        name: "date"
        picker_utc: false # 确保使用本地时区
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ" # 关键是这里
        time_format: "HH:mm:ss"        # 确保时间部分是可编辑的
      - {label: "正文内容", name: "body", widget: "markdown"}
      - {label: "设为草稿", name: "draft", widget: "boolean", default: false}