# 已净化的配置文件
backend:
  name: github
  repo: void-echo/yu
  branch: main
  # auth_type: pkce
  # app_id: Ov23li6e6Al0wxYfIIR6

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "文章标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文内容", name: "body", widget: "markdown"}
      - {label: "设为草稿", name: "draft", widget: "boolean", default: true}